theme = "modern" #"solarized-dark"
icons = "awesome"

######################
## System Resources ##
######################

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20.0
warning = 15.0
alert = 5

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 40.0
alert = 20.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "temperature"
collapsed = true
interval = 2
format = "{min}°↓ {max}°↑ {average}°≈"

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "load"
interval = 2
format = "{1m}"

################
## Essentials ##
################

[[block]]
block = "networkmanager"
on_click = "termite --class float -e nmtui"
ap_format = "{strength}%"
device_format = "{icon}{ap}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
on_click = "pavucontrol" 

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "custom"
command = "/usr/local/bin/printlang.sh"
interval = 1



[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R "
on_click="/usr/local/bin/openCalendar.sh"
