theme = "modern"
icons = "awesome"

[[block]]
block = "uptime"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "custom"
command = "/bin/node ~/.config/scripts/getBrightness.js"
interval = 1
json = true

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R "
on_click = "/usr/local/bin/openCalendar.sh"

